version: "3.2"
services:
  product:
      build: 
        context: ./CoreServices/
        args:
          PORT: 18081
          FOLDER: Product
      networks:
        - local_dev_net
      ports:
        - '18081:18081'
      depends_on: 
        - db
  category: 
    build: 
      context: ./CoreServices
      args:
        PORT: 18082
        FOLDER: Category
    ports:
      - '18082:18082'
    networks:
      - local_dev_net
    depends_on:
      - db
  user:
    build: 
      context: ./CoreServices
      args:
        PORT: 18083
        FOLDER: User
    networks:
      - local_dev_net
    ports:
      - '18083:18083'
    depends_on: 
      - db
  db:
    build: ./db
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3306:3306"
    networks:
      local_dev_net:
        aliases:
          - database
networks:
  local_dev_net:
    driver: bridge
