server:
    port: 18081
spring:
    application:
        name: product-service
    datasource:
        url: jdbc:mysql://localhost:3306/product
        username: root
        password: c8de110f37300a53a971749
        driver-class-name: com.mysql.cj.jdbc.Driver
# ---
# spring:
#     config:
#         activate: 
#             on-profile: docker
#     datasource:
#         url: jdbc:mysql://database:3306/product  