server:
    port: 18081
spring:
    application:
        name: product-service
    datasource:
        url: jdbc:mysql://localhost:3306/webshop
        username: webshopuser
        password: 240b2c6d58ff2ce2f508b49f
        driver-class-name: com.mysql.cj.jdbc.Driver
    