server:
  port: 18085
  servlet:
    context-path: "/auth"

spring:
  application:
    name: auth-server

security:
  oauth2:
    client:
      client-id: 1234
      client-secret: test
      auth-server-client-credentials:
        access-token-uri: http://localhost:18085/auth/oauth/token
        client-id: AuthServer
        client-secret: secret
        grant-type: client_credentials
        scope: read

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 20
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
      springframework:
        security:
          web:
            access: DEBUG
          oauth2: DEBUG
        web:
          client:
            RestTemplate: DEBUG
          servlet:
            DispatcherServlet: DEBUG

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  oauth2:
    client:
      auth-server-client-credentials:
        access-token-uri: http://auth:18085/auth/oauth/token
