server:
  port: 18085
  servlet:
    context-path: "/auth"
spring:
  application:
    name: auth-server
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
security:
  oauth2:
    client:
      client-id: 1234
      client-secret: test
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/