server:
  port: 8081

spring:
  application:
    name: zuul

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:18085/auth/oauth2/keys

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 20
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

ribbon:
  ServerListRefreshInterval: 2000
  ReadTimeout: 6000
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1
      metrics:
        rollingStats:
          timeInMilliseconds: 30000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  dashboard:
    proxy-stream-allow-list: "*"

turbine:
  appConfig: zuul, user-service, product-category-composite-service
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default

zuul:
  sensitiveHeaders:
  ignoredServices: "*"
  prefix: /webshop-api
  routes:
    product-service:
      path: /productsCore/**
      stripPrefix: true
    category-service:
      path: /categoryCore/**
      stripPrefix: true
    user-service:
      path: /users/**
      stripPrefix: false
    composite-products:
      service-id: product-category-composite-service
      path: /products/**
      stripPrefix: false
    composite-categories:
      service-id: product-category-composite-service
      path: /categories/**
      stripPrefix: false
    auth-server:
      path: /auth/**
      stripPrefix: false

logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
      springframework:
        security:
          web:
            access: DEBUG
          oauth2: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://auth:18085/auth/oauth2/keys
