server:
  port: 8081

spring:
  application:
    name: zuul

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # Increase the Hystrix timeout to 60s (globally)
            timeoutInMilliseconds: 60000
  dashboard:
    proxy-stream-allow-list: "*"

turbine:
  appConfig: zuul, user-service, product-category-composite-service
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
zuul:
  ignoredServices: "*"
  prefix: /webshop-api
  routes:
    product-service:
      path: /productsCore/**
      stripPrefix: true
    category-service:
      path: /categoryCore/**
      stripPrefix: true
    user-service:
      path: /users/**
      stripPrefix: false
    product-category-composite-service:
      path: /products/**
      stripPrefix: false
    composite:
      service-id: product-category-composite-service
      path: /categories/**
      stripPrefix: false

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
