insert into category.category (`id`, `name`) values (3, 'Ressource');	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Holz', 15, 3, 'Holzfällerhütte');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kartoffeln', 7, 3, 'Kartoffelfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Wolle', 5, 3, 'Schaffarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Lehm', 20, 3, 'Lehmgrube');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Schweine', 18, 3, 'Schweinefarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Weizen', 17, 3, 'Weizenfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Eisen', 8, 3, 'Eisenmine');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kohle', 13, 3, 'Kohlemine / Köhlerhütte');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Hopfen', 11, 3, 'Hopfenfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Quarzsand', 2, 3, 'Sandmine');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Rindfleisch', 15, 3, 'Rinderfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Paprika', 19, 3, 'Paprikafarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Felle', 2, 3, 'Jagdhütte');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Zement', 5, 3, 'Zement Miene');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Öl', 17, 3, 'Ölraffinerie');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kupfer', 13, 3, 'Kupfermine');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Zink', 5, 3, 'Zinkmine');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Salpeter', 19, 3, 'Saltpeter Works');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Trauben', 17, 3, 'Weinberg');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Holz', 19, 3, 'Holzfällerhütte');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Fischöl', 10, 3, 'Fischölfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Bananen', 11, 3, 'Bananenplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Zuckerrohr', 10, 3, 'Zuckerrohrplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Baumwolle', 18, 3, 'Baumwollplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Perlen', 17, 3, 'Perlenfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Alpaka Wolle', 8, 3, 'Alpakafarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kautschuk', 20, 3, 'Kautschukplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Lehm', 14, 3, 'Lehmgrube');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Mais', 17, 3, 'Maisfarm');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kaffeebohnen', 14, 3, 'Kaffeeplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Gold', 17, 3, 'Goldmine');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Öl', 7, 3, 'Ölraffinerie');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Tabak', 3, 3, 'Tabakplantage');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kakao', 12, 3, 'Kakaoplantage');
insert into category.category (`id`, `name`) values (4, 'Rohstoff');	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Segel', 15, 4, 'Segelmacher');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Mehl', 5, 4, 'Mühle');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Talg', 11, 4, 'Wachsmeisterei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Stahl', 3, 4, 'Hochofen');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Malz', 18, 4, 'Mälzerei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Glas', 24, 4, 'Glaserei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Gulasch', 6, 4, 'Großküche');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Messing', 11, 4, 'Brass Smeltery');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Dynamit', 24, 4, 'Dynamitfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Dampfmaschinen', 11, 4, 'Motor Assembly Line');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Gold', 16, 4, 'Goldschmiede');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Glühfäden', 9, 4, 'Glühfädenfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Holzfurnier', 12, 4, 'Marquetry Workshop');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Fahrgestell', 9, 4, 'Coachmakers');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Baumwollstoff', 25, 4, 'Cotton Mill');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Segel', 19, 4, 'Segelmacher');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Filz', 13, 4, 'Felt Producer');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Holzfurnier', 19, 4, 'Marquetry Workshop');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Zucker', 27, 4, 'Zuckerraffinerie');
insert into category.category (`id`, `name`) values (5, 'Baumaterial');	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Bretter', 23, 5, 'Sägewerk');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Ziegel', 13, 5, 'Ziegelfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Stahlträger', 12, 5, 'Steelworks');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kanonen', 29, 5, 'Kanonengießerei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Fenster', 29, 5, 'Fenstermacherei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Beton', 22, 5, 'Betonfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Schwere Waffen', 17, 5, 'Heavy Weapons Factory');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Bretter', 9, 5, 'Sägewerk');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Ziegel', 25, 5, 'Ziegelfabrik');
insert into category.category (`id`, `name`) values (6, 'Grundbedürfnis');	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Fisch', 50, 6, 'Fischerei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Arbeitskleidung', 26, 6, 'Weberei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Wurst', 12, 6, 'Schlachter');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Brot', 50, 6, 'Bäckerei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Seife', 32, 6, 'Siederei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Fleischkonserven', 39, 6, 'Büchsenmacher');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Nähmaschine', 39, 6, 'Nähmaschinen Fabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Pelzmäntel', 22, 6, 'Fur Dealer');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Brillen', 32, 6, 'Brillenfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Glühbirnen', 41, 6, 'Light Bulb Factory');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Sekt', 28, 6, 'Champagne Cellar');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Dampfwagen', 45, 6, 'Cab Assembly Line');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Gebackene Bananen', 45, 6, 'Fried Plantain Kitchen');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Ponchos', 27, 6, 'Poncho Darner');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Tortillas', 49, 6, 'Tortilla Maker');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Kaffee', 40, 6, 'Kaffeerösterei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Hüte', 15, 6, 'Bomb­ín Weaver');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Zigarren', 21, 6, 'Zigarrenfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Schokolade', 19, 6, 'Schokoladenfabrik');
insert into category.category (`id`, `name`) values (7, 'Luxusbedürfnis');	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Schnaps', 44, 7, 'Schnapsdestillerie');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Bier', 52, 7, 'Brauerei');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Hochräder', 13, 7, 'Fahrradfabrik');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Taschenuhren', 35, 7, 'Uhrmacher');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Schmuck', 11, 7, 'Juwelier');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Phonographen', 27, 7, 'Gramophone Factory');
	insert into product.product (`name`, `price`, `category_id`, `details`) values ('Rum', 35, 7, 'Rumdestillerie');
