server:
  port: 18083
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: c8de110f37300a53a971749
    hikari:
      initialization-fail-timeout: 70000
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 20
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

ribbon:
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # Increase the Hystrix timeout to 15s (globally)
            timeoutInMilliseconds: 15000

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://database:3306/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

---
spring:
  profiles: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1

eureka:
  client:
    enabled: false
