server:
  port: 18083

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: c8de110f37300a53a971749
    hikari:
      initialization-fail-timeout: 70000
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:18085/auth/oauth2/keys

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 20
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org:
      apache:
        coyote: 
          http11:
            Http11InputBuffer: DEBUG
      springframework:
        security:
          web:
            access: DEBUG
          oauth2: DEBUG
        web:
          client:
            RestTemplate: DEBUG

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://database:3306/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://auth:18085/auth/oauth2/keys

---
spring:
  profiles: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1

---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1

eureka:
  client:
    enabled: false
