server:
    port: 18082
spring:
    application:
        name: category-service
    datasource:
        url: jdbc:mysql://localhost:3306/category
        username: root
        password: c8de110f37300a53a971749
        driver-class-name: com.mysql.cj.jdbc.Driver
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"

---
spring:
    config:
        activate: 
            on-profile: docker
    datasource:
        url: jdbc:mysql://database:3306/category
