server:
  port: 18082
spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:3306/category
    username: root
    password: c8de110f37300a53a971749
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: '${spring.application.name}:${random.value}'
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://database:3306/category
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
