server:
  port: 18082
spring:
  application:
    name: category-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/category
    username: root
    password: c8de110f37300a53a971749
    hikari:
      initialization-fail-timeout: 70000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 20
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://database:3306/category
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

---
spring:
  profiles: h2memdb
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

#hibernate.show_sql=true
#hibernate.hbm2ddl.auto=create-drop
#hibernate.cache.use_second_level_cache=true
#hibernate.cache.use_query_cache=true
#hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory

---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
eureka:
  client:
    enabled: false
