server:
    port: 18082
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://localhost:3306/user
        username: root
        password: c8de110f37300a53a971749
        driver-class-name: com.mysql.cj.jdbc.Driver
    