server:
  port: 18084
  ribbon:
    eureka:
      enabled: true

spring:
  application:
    name: product-category-composite-service

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

ribbon:
  ReadTimeout: 3000

hystrix:
  command:
    default:
      ciruitBreaker:
        requestVolumeTreshold: 2
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 30000
      execution:
        isolation:
          thread:
            # Increase the Hystrix timeout to 10s (globally)
            timeoutInMilliseconds: 10000

logging:
  level:
    com:
      netflix:
        loadbalancer:
          DynamicServerListLoadBalancer: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
