server:
  port: 18084
  ribbon:
    eureka:
      enabled: true

spring:
  application:
    name: product-category-composite-service
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:18085/auth/oauth2/keys
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

ribbon:
  ServerListRefreshInterval: 2000
  ReadTimeout: 2000
  ConnectTimeout: 1000

hystrix:
  command:
    default:
      ciruitBreaker:
        requestVolumeThreshold: 1
      metrics:
        rollingStats:
          timeInMilliseconds: 30000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    deleteCategory:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
    com:
      netflix:
        loadbalancer:
          DynamicServerListLoadBalancer: INFO
    org:
      springframework:
        web:
          security: DEBUG
          client:
            RestTemplate: DEBUG
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
