server:
  port: 18084
  ribbon:
    eureka:
      enabled: true
spring:
  application:
    name: product-category-composite-service
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: '${spring.application.name}:${random.value}'
management:
  endpoint:
    health: 
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
      cors:
        allowed-origins: true
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: '${spring.application.name}:${random.value}'